"""initial migration

Revision ID: 6b629919798f
Revises: 
Create Date: 2024-04-27 00:47:32.106446

"""
import random
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash

# revision identifiers, used by Alembic.
revision = '6b629919798f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###   
    op.drop_table('programs')
    op.drop_table('users')
    op.drop_table('channels')
     
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('weekday', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', name='weekday'), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    channels = 6
    # Adding initial data
    op.execute(
        'INSERT INTO channels (title) VALUES\n'+\
        ','.join(f"('Канал {x}')"for x in range(1,channels+1))
    )

    op.execute(
        'INSERT INTO programs (title, start_time, weekday, channel_id) VALUES\n'+\
        ','.join(','.join(\
        f"('Програма {random.randint(1,99)}','{str(random.randint(1,23)).zfill(2)}:00:00','{y}',{x%channels+1})"\
        for x in range(1,7*channels+1)) for y in ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
                                            'Friday', 'Saturday', 'Sunday'])
    )
    
    op.execute(
        f"""
        INSERT INTO users (email, name, password, is_superuser) VALUES 
        ('admin@admin.com', 'admin', '{generate_password_hash('admin', method='pbkdf2:sha1')}', true),
        ('user@user.com', 'user', '{generate_password_hash('user', method='pbkdf2:sha1')}', false)
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    op.drop_table('users')
    op.drop_table('channels')
    # ### end Alembic commands
